load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "calendar_calendar",
    module_name = "CalendarCalendar",
    srcs = glob(["**/*.swift"]),
    visibility = ["//visibility:public"],
    private_deps = [
        "//Srcs/Common:common_tools",
    ]
)
